#![deny(unsafe_code)]
//! Proof of Thought watcher library.
//!
//! Permissionless service that subscribes to Solana program logs,
//! fetches off-chain reasoning traces, verifies them, and files
//! fraud-proof challenges to slash misbehaving agents.
//!
//! TODO(post-merge): replace hand-rolled Anchor event/ix discriminator and
//! struct layouts with the real IDL types generated by the `pot_program`
//! crate from the sibling worktree (`.worktrees/program` on `feat/program`).

pub mod challenge;
pub mod config;
pub mod subscribe;
pub mod trace_fetch;
pub mod types;
pub mod verify;

pub use challenge::{ChallengeFiler, ChallengeSubmitter, MockChallengeSubmitter};
pub use config::{BondStrategy, StorageBackend, WatcherConfig};
pub use subscribe::{LogStream, MockLogStream, WebsocketLogStream};
pub use trace_fetch::{ArweaveFetcher, MockFetcher, ShadowFetcher, TraceBundle, TraceFetcher};
pub use types::{
    ChallengeClaim, Policy, ThoughtRecord, ThoughtStatus, ThoughtSubmittedEvent,
    THOUGHT_SUBMITTED_DISCRIMINATOR,
};
pub use verify::{VerifyOutcome, Verifier};
